### ISSUE TITLE
Export each env's var pool size as a RGBASM constant

### ISSUE THREAD

**Issue by ISSOtm** [evie-calico/evscript#11]
Notably, this allows other RGBASM code to write a single `ds TheEnv__pool_size` (or similar) statement, without having to worry about two sources of truth.

**Comment by evie-calico** [comment]
Since environments are included in multiple files, this would create conflicting definitions.

I could output these constants only in "root" (not included) files, and then expect the user to link in their "header" output (which would only contain the pool sizes); does that work?

**Comment by evie-calico** [comment]
Closed by 859760a

**Comment by ISSOtm** [comment]
This brings into consideration whether it would be useful to let RGBLINK accept several exported definitions of the same constant if they all agree... (not labels, only sections).
